### ISSUE TITLE
openai.error.InvalidRequestError, requested too many tokens

### ISSUE THREAD

**Issue by chrismarquardt** [Methexis-Inc/terminal-copilot#14]
Worked great the other day, now I'm getting this, no matter the command:

openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 6365 tokens (6109 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

**Comment by JoelKronander** [comment]
Hi @chrismarquardt 

Sorry about that it seems your prompt got very long. Are you using the latest version terminal-copilot 1.0.7?

Could you run with the -v flag to see the prompt that gets sent to openai to help us debug?

**Comment by rafpaf** [comment]
I ran into this problem when using copilot in a directory that contained a lot of hidden files. Once I deleted the files the problem went away.

**Comment by 2mawi2** [comment]
Yes `directory_list = os.listdir()` currently has no limits. If you have a lot of directories and files. We could add a max limit to the directory context.

**Comment by 2mawi2** [comment]
Implemented in #44
