### ISSUE TITLE
syntax error in suggested environment variable set

### ISSUE THREAD

**Issue by alexxcollins** [Methexis-Inc/terminal-copilot#3]
On first use, it is helpfully suggested to export the OpenAI key.

Line 60:
`print("export OPENAI_API_KEY = <your key>")`

Following this exactly give an error:  "zsh: bad assignment"

If you remove the spaces from the export suggestion, users won't have to google the correct syntax:

`print("export OPENAI_API_KEY=<your key>")`

Thanks for building a great little tool :-)

**Comment by JoelKronander** [comment]
Thanks! Great find! Fixed!
