### ISSUE TITLE
serious security issue with earlier version (1.2.2)

### ISSUE THREAD

**Issue by rafpaf** [Methexis-Inc/terminal-copilot#38]
In version 1.2.2, `terminal-copilot` sends the last 40 commands in your history to OpenAI, even if the `--history` flag is not present. This bug has been fixed in version 1.2.3 – thank you to the authors for finding and solving it. I wonder if there is a way to notify people who downloaded the earlier version.

**Comment by JoelKronander** [comment]
I don't think there is an easy way, we made sure to update the pip package etc.
