### ISSUE TITLE
Security issue with exposing env variables to OpenAI

### ISSUE THREAD

**Issue by amir-abdi** [Methexis-Inc/terminal-copilot#4]
Why does the prompt need env vars to come up with the right command?

Concern: Credentials are often stored in env variables. 

Recommendation: I'd recommend against including env vars unless absolutely necessary.

**Comment by JoelKronander** [comment]
Only three env variables are used. The three used are often helpful. 

Are you thinking of something else?

**Comment by amir-abdi** [comment]
Referring to this: https://github.com/Methexis-Inc/terminal-copilot/blob/main/copilot/copilot.py#L50

**Comment by amir-abdi** [comment]
Oh, excuse my carelessness in reviewing your code. I'll close the issue.
