### ISSUE TITLE
Doesn't work in bash, in Linux

### ISSUE THREAD

**Issue by jsribeiro** [Methexis-Inc/terminal-copilot#7]
After seeing the code, I understand you're asking ChatGPT for commands for zsh in macOS.

You should either detect the OS and shell being used, make it clear the environment is not supported when running the command, or at least make it clear on the documentation/README that this is the case.

Currently failing on bash actually because it can't find the "alias" command (which is a builtin in bash, not a command).

**Comment by JoelKronander** [comment]
Thanks! Fixed!

Let me know if I missed something, and it still dosen't work @jsribeiro
